name: firebase destribution

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.10
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.0'
      - name: Clean Flutter
        run: flutter clean
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Flutter Pub Get with Verbose
        run: flutter pub get
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json
      - name: Run
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.jks
      - name: Decode firebase_option
        env:
        firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - name: Build APK
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          flutter build apk --release
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APPID}}
          serviceCredentialsFileContent: ${{ secrets.GCPAPI }}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk
